// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgGkt6R-R-5_6T5vo6cn2CcY4cTa3prD8',
    appId: '1:880103538034:web:00c53097b4f40c37ad31eb',
    messagingSenderId: '880103538034',
    projectId: 'brew-crew-de2e7',
    authDomain: 'brew-crew-de2e7.firebaseapp.com',
    storageBucket: 'brew-crew-de2e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrzalxL_xaiaMptCG0og9clUdl7jx5sVU',
    appId: '1:880103538034:android:6848dfb00e808540ad31eb',
    messagingSenderId: '880103538034',
    projectId: 'brew-crew-de2e7',
    storageBucket: 'brew-crew-de2e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdqZZKl0oFu15SYKrgKX6O3651aRT8l-M',
    appId: '1:880103538034:ios:9c5053ac69e871c1ad31eb',
    messagingSenderId: '880103538034',
    projectId: 'brew-crew-de2e7',
    storageBucket: 'brew-crew-de2e7.firebasestorage.app',
    iosBundleId: 'dev.yellowtech.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdqZZKl0oFu15SYKrgKX6O3651aRT8l-M',
    appId: '1:880103538034:ios:9c5053ac69e871c1ad31eb',
    messagingSenderId: '880103538034',
    projectId: 'brew-crew-de2e7',
    storageBucket: 'brew-crew-de2e7.firebasestorage.app',
    iosBundleId: 'dev.yellowtech.brewCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgGkt6R-R-5_6T5vo6cn2CcY4cTa3prD8',
    appId: '1:880103538034:web:29bcd7372050de64ad31eb',
    messagingSenderId: '880103538034',
    projectId: 'brew-crew-de2e7',
    authDomain: 'brew-crew-de2e7.firebaseapp.com',
    storageBucket: 'brew-crew-de2e7.firebasestorage.app',
  );
}
